# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class InspectSchemaAction(BaseModel):
    action: typing.Optional[typing_extensions.Literal['inspect_schema']] = None

class RunSqlQueryAction(BaseModel):
    action: typing.Optional[typing_extensions.Literal['run_sql_query']] = None
    sql: typing.Optional[str] = Field(default=None, description='SQLite query to execute against the temporary task database.')

class SqlAgentDecision(BaseModel):
    draft: typing.Optional[str] = Field(default=None, description='Short chain-of-draft plan for this single next step. Keep it under 18 words.')
    output: typing.Optional[typing.Union["InspectSchemaAction", "RunSqlQueryAction", "SubmitSqlAction"]] = Field(default=None, description='Exactly one executable harness action.')

class SqlAgentMessage(BaseModel):
    role: typing.Optional[typing.Union[typing_extensions.Literal['system'], typing_extensions.Literal['user'], typing_extensions.Literal['assistant']]] = None
    content: typing.Optional[str] = None

class SubmitSqlAction(BaseModel):
    action: typing.Optional[typing_extensions.Literal['submit_sql']] = None
    sql: typing.List[str] = Field(description='Final SQLite statement or statements to submit for hidden tests.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
