# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (5)
# #########################################################################

class InspectSchemaAction(BaseModel):
    action: typing_extensions.Literal['inspect_schema']

class RunSqlQueryAction(BaseModel):
    action: typing_extensions.Literal['run_sql_query']
    sql: str = Field(description='SQLite query to execute against the temporary task database.')

class SqlAgentDecision(BaseModel):
    draft: str = Field(description='Short chain-of-draft plan for this single next step. Keep it under 18 words.')
    output: typing.Union["InspectSchemaAction", "RunSqlQueryAction", "SubmitSqlAction"] = Field(description='Exactly one executable harness action.')

class SqlAgentMessage(BaseModel):
    role: typing.Union[typing_extensions.Literal['system'], typing_extensions.Literal['user'], typing_extensions.Literal['assistant']]
    content: str

class SubmitSqlAction(BaseModel):
    action: typing_extensions.Literal['submit_sql']
    sql: typing.List[str] = Field(description='Final SQLite statement or statements to submit for hidden tests.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
