# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.InspectSchemaAction": types.InspectSchemaAction,
    "stream_types.InspectSchemaAction": stream_types.InspectSchemaAction,

    "types.RunSqlQueryAction": types.RunSqlQueryAction,
    "stream_types.RunSqlQueryAction": stream_types.RunSqlQueryAction,

    "types.SqlAgentDecision": types.SqlAgentDecision,
    "stream_types.SqlAgentDecision": stream_types.SqlAgentDecision,

    "types.SqlAgentMessage": types.SqlAgentMessage,
    "stream_types.SqlAgentMessage": stream_types.SqlAgentMessage,

    "types.SubmitSqlAction": types.SubmitSqlAction,
    "stream_types.SubmitSqlAction": stream_types.SubmitSqlAction,


}